const products = [
  {
    id: 1,
    images: "/img/product/camisa-hombre-1.jpg",
    nombre: "TRAJE SS100 SATÉN",
    color: "Marron Oscuro",
    cuotas: 3,
    precio: 3000,
    precioSinDescuento: 3510,
    descuento: 17,
    precioCuotas: 1000,
  },
  {
    id: 2,
    images: "/img/product/camisa-hombre-2.jpg",
    nombre: "TRAJE SS100 SATÉN",
    color: "Bordo Brillante",
    cuotas: 3,
    precio: 3000,
    precioSinDescuento: 3510,
    descuento: 17,
    precioCuotas: 1000,
  },
  {
    id: 3,
    images: "/img/product/camisa-hombre-3.jpg",
    nombre: "TRAJE SS100 SATÉN",
    color: "Marron Claro",
    cuotas: 3,
    precio: 3000,
    precioSinDescuento: 3510,
    descuento: 17,
    precioCuotas: 1000,
  },
  {
    id: 4,
    images: "/img/product/camisa-hombre-4.jpg",
    nombre: "TRAJE SS100 SATÉN",
    color: "Blanco",
    cuotas: 3,
    precio: 3000,
    precioSinDescuento: 3510,
    descuento: 17,
    precioCuotas: 1000,
  },
  {
    id: 5,
    images: "/img/product/camisa-hombre-5.jpg",
    nombre: "TRAJE SS100 SATÉN",
    color: "Purpura",
    cuotas: 3,
    precio: 3000,
    precioSinDescuento: 3510,
    descuento: 17,
    precioCuotas: 1000,
  },
  {
    id: 6,
    images: "/img/product/camisa-hombre-6.jpg",
    nombre: "TRAJE SS100 SATÉN",
    color: "Gris",
    cuotas: 3,
    precio: 3000,
    precioSinDescuento: 3510,
    descuento: 17,
    precioCuotas: 1000,
  },
  {
    id: 7,
    images: "/img/product/camisa-hombre-1.jpg",
    nombre: "TRAJE SS100 SATÉN",
    color: "Marron Oscuro",
    cuotas: 3,
    precio: 3000,
    precioSinDescuento: 3510,
    descuento: 17,
    precioCuotas: 1000,
  },
  {
    id: 8,
    images: "/img/product/camisa-hombre-2.jpg",
    nombre: "TRAJE SS100 SATÉN",
    color: "Bordo Brillante",
    cuotas: 3,
    precio: 3000,
    precioSinDescuento: 3510,
    descuento: 17,
    precioCuotas: 1000,
  },
];

module.exports = products;
